# Generated by Django 3.1.6 on 2021-03-10 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sabor',
            old_name='nome',
            new_name='sabor',
        ),
    ]
