# Generated by Django 3.1.6 on 2021-02-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_remove_produto_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='tamanho',
            field=models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], max_length=10),
        ),
    ]
