# Generated by Django 3.1.6 on 2021-02-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produto', '0002_type_tamanho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='type',
            field=models.CharField(max_length=255, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='Type',
        ),
    ]
