# Generated by Django 3.1.6 on 2021-02-21 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_auto_20210221_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(default=' ', help_text='Observação', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itempedido',
            name='quantidade',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
