# Generated by Django 3.1.6 on 2021-02-21 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_auto_20210221_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='observacao',
            field=models.CharField(blank=True, help_text='Observação', max_length=30, null=True),
        ),
    ]
